name: decryptor
description: "A Flutter application for decrypting PDF files using RSA and AES."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  pointycastle: ^3.9.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  provider: ^6.1.1
  window_manager: ^0.3.8
  desktop_drop: ^0.4.4
  path: ^1.8.3
  shared_preferences: ^2.2.2
  flutter_acrylic: ^1.1.4
  asn1lib: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
